package com.xxmrk888ytxx.privatenote.Utils

object AnalyticsEvents {
    const val SELECT_IMAGE_EVENT = "SELECT_IMAGE_EVENT"
    const val SELECT_IMAGE_EVENT_OK = "SELECT_IMAGE_EVENT_OK"
    const val SELECT_IMAGE_EVENT_ERROR = "SELECT_IMAGE_EVENT_ERROR"
    const val Remove_Note_event = "Remove_Note_event"
    const val Add_or_update_note_event = "add_or_update_note_event"
    const val Change_category_event = "Change_category_event"
    const val Add_Note_Image_Event = "Add_Note_Image_Event"
    const val Load_Images_Event = "Load_Images_Event"
    const val Change_tempDir_to_Image_Event = "Change_tempDir_to_Image_Event"
    const val Remove_Image_Event = "Remove_Image_Event"
    const val Clear_Load_Images = "Clear_Load_Images"
    const val Add_Category_Event = "Add_Category_Event"
    const val Remove_Category_Event = "Remove_Category_Event"
    const val Update_Category_Event = "Update_Category_Event"
    const val Insert_Todo_Event = "Insert_Todo_Event"
    const val Remove_Todo_Event = "Remove_Todo_Event"
    const val Change_Mark_Status = "Change_Mark_Status"
    const val Add_NotifyTask = "Add_NotifyTask"
    const val Remove_NotifyTask = "Remove_NotifyTask"
    const val Remove_NotifyTask_By_TodoId = "Remove_NotifyTask_By_TodoId"
    const val Send_Biometric_Authorization_Request = "Send_Biometric_Authorization_Request"
    const val Check_Available_FingerPrint = "Check_Available_FingerPrint"
    const val Biometric_Authorization_Error = "Biometric_Authorization_Error"
    const val Biometric_Authorization_Succeeded = "Biometric_Authorization_Succeeded"
    const val Biometric_Authorization_Failed = "Biometric_Authorization_Failed"
    const val Show_Category_List = "Show_Category_List"
    const val Hide_Category_List = "Hide_Category_List"
    const val Show_EditCategory_Dialog = "Show_EditCategory_Dialog"
    const val Hide_EditCategory_Dialog = "Hide_EditCategory_Dialog"
    const val Remove_Category = "Remove_Category"
    const val SearchMode_In_NoteScreen = "SearchMode_In_NoteScreen"
    const val BackToDefaultMode_In_NoteScreen = "BackToDefaultMode_In_NoteScreen"
    const val SelectionMode_In_NoteScreen = "SelectionMode_In_NoteScreen"
}